apiVersion: v1
kind: ReplicationController
metadata:
  name: sql
spec:
  replicas: 3
  selector:
    app: sql
  template:
    metadata:
      name: sql
      labels:
        app: sql
    spec:
      containers:
      - name: sql
        image: sql
        ports:
        - containerPort: 6060